### ISSUE TITLE
Scaden process issue

### ISSUE THREAD

**Issue by ThomasThaewel** [KevinMenden/scaden#116]
Dear Kevin,
I used scaden simulate with an h5ad object to generate my training data. Then I created the text file for the bulk data with the example in mind(rows_index=Genes/columns=samples). However when I try to run scaden process I get this error:

scaden process data.h5ad scaden_bulk.text

Traceback (most recent call last):
  File "/Users/ty176/opt/miniconda3/envs/scaden/bin/scaden", line 8, in <module>
    sys.exit(main())
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/scaden/__main__.py", line 48, in main
    cli()
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/scaden/__main__.py", line 155, in process
    processing(
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/scaden/process.py", line 35, in processing
    preprocess_h5ad_data(raw_input_path=training_data,
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/scaden/model/functions.py", line 67, in preprocess_h5ad_data
    raw_input.X = sample_scaling(raw_input.X, scaling_option)
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/anndata/_core/anndata.py", line 618, in X
    _subset(self._adata_ref.X, (self._oidx, self._vidx)),
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/ty176/opt/miniconda3/envs/scaden/lib/python3.9/site-packages/anndata/_core/index.py", line 127, in _subset
    return a[subset_idx]
IndexError: arrays used as indices must be of integer (or boolean) type
 

I am not sure what I did wrong in terms of the input files, do you maybe have an Idea what to change here?
Thanks a lot

**Comment by HuringdaCat** [comment]
Having the same issue...
