### ISSUE TITLE
Problem with Scaden process

### ISSUE THREAD

**Issue by idalarsson** [KevinMenden/scaden#39]
Hi! I'm back with a new issue. While trying to run the Scaden process command I get this error:

```
p209-114:preprocessing idala384$ scaden process barcoding.h5ad DMSO_3.txt

     ____                _            
    / ___|  ___ __ _  __| | ___ _ __  
    \___ \ / __/ _` |/ _` |/ _ \ '_ \ 
     ___) | (_| (_| | (_| |  __/ | | |
    |____/ \___\__,_|\__,_|\___|_| |_|

    
Found 0 common genes.
Pre-processing raw data ...
Subsetting genes ...
Traceback (most recent call last):
  File "/usr/local/bin/scaden", line 13, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/scaden/cli.py", line 137, in main
    cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/scaden/cli.py", line 121, in process
    processing(data_path=prediction_data,
  File "/usr/local/lib/python3.8/site-packages/scaden/scaden_main.py", line 165, in processing
    preprocess_h5ad_data(raw_input_path=training_data,
  File "/usr/local/lib/python3.8/site-packages/scaden/model/functions.py", line 60, in preprocess_h5ad_data
    raw_input = raw_input[:, sig_genes]
  File "/usr/local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1088, in __getitem__
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/usr/local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 305, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/usr/local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 348, in _init_as_view
    self._varm = adata_ref.varm._view(self, (vidx,))
  File "/usr/local/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py", line 92, in _view
    return self._view_class(self, parent, subset_idx)
  File "/usr/local/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py", line 246, in __init__
    self.dim_names = parent_mapping.dim_names[subset_idx]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4111, in __getitem__
    result = getitem(key)
IndexError: arrays used as indices must be of integer (or boolean) type
```

I guess the problem is that it cannot find any common genes between the training data and prediction data. I've formatted the prediction files as you described (genes as rows, samples as columns, tab-delimited). Any ideas?

**Comment by KevinMenden** [comment]
Hi Ida,

wow, you really have a hard time with the package ... really sorry for that!! 

Yes it seems like that is the issue ... it's hard to tell, would it be possible for you to send me those files? (could do it by e-mail to kevin.menden@t-online.de).
Alternatively, if that's not possible, you could send me just the header of the files or something like this, so I can have a look what's going on or ideally try to reproduce the error.

Bw,
kevin

**Comment by idalarsson** [comment]
Yes, seems like I'm the corner case we all fear... ;)

I sent you an email, thank you for helping me with this!

**Comment by HuringdaCat** [comment]
Hi, I'm having the exact same error now... Can I have some advice on this? I'm wondering how was the issue solved here. Thanks!
