### ISSUE TITLE
No 'simulate' command in docker image? And doc for h5da file content

### ISSUE THREAD

**Issue by vdet** [KevinMenden/scaden#51]
Hello,

I am trying to run Scaden from the docker image on OSX.

The scaden command is found and version is 1.0.0. 

Now, following the example from [this page](https://github.com/KevinMenden/scaden/blob/master/docs/usage.md),
I run
`scaden simulate --cells 100 --n_samples 1000 --data preprocessing`
and got quite a few FutureWarnings and this error:
```
Usage: scaden [OPTIONS] COMMAND [ARGS]...
Try 'scaden --help' for help.

Error: No such command 'simulate'.
```
Is the container (installed with 'docker pull kevinmenden/scaden' last Friday, Dec 11th) up to date?

In addition, I'll have to write my own bulk simulator for my specific application. It would be very useful to get a description of whatthe h5da file provided to train, and/or toy examples of inputs for create_h5ad_file.py contains. As a R programmer this would also save me the trouble to write the simulated bulk data to file and generate directly the h5da file.

Nevertheless, I was actually able run create_h5ad_file.py on the file I generated in R:
```
python ../../../scaden/scaden-master/scaden/preprocessing/create_h5ad_file.py --data ./preprocessing/ --out ./preprocessing/train.h5ad
Celltypes: ['c5', 'c11', 'c9', 'c16', 'c2', 'c14', 'c3', 'c18', 'c19', 'c20', 'c10', 'c12', 'c22', 'c17', 'c8', 'c21', 'c13', 'c7', 'c4', 'c1', 'c15', 'c6', 'c0']
```
No error message, and file train.h5da is created and non empty. But when I next running 'scaden train', i got an error:
```
scaden train ./preprocessing/train.h5ad --steps 20000    
Processing TESTSAMPLE
/opt/conda/lib/python3.7/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
... storing 'ds' as categorical
(base) root@e4ff2c3d5805:/Volumes/VD-MISC-2TB/ST/experiments/PTC7SN1/scaden_proportion_model# scaden train ./preprocessing/train.h5ad --steps 20000
/opt/conda/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/envs/scaden/lib/python3.6/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
/opt/conda/envs/scaden/lib/python3.6/site-packages/scanpy/api/__init__.py:6: FutureWarning: 

In a future version of Scanpy, `scanpy.api` will be removed.
Simply use `import scanpy as sc` and `import scanpy.external as sce` instead.

  FutureWarning
Training on: []
Training M256 Model ...
2020-12-12 09:41:01.301049: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-12-12 09:41:01.327354: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/opt/conda/envs/scaden/bin/scaden", line 125, in <module>
    cli()
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/scaden/bin/scaden", line 63, in train
    num_steps=steps)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/scaden/scaden_main.py", line 64, in training
    cdn256.train(input_path=data_path, train_datasets=train_datasets)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/scaden/model/scaden.py", line 252, in train
    self.build_model(input_path=input_path, train_datasets=train_datasets, mode="train")
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/scaden/model/scaden.py", line 213, in build_model
    self.load_h5ad_file(input_path=input_path, batch_size=self.batch_size, datasets=train_datasets)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/scaden/model/scaden.py", line 151, in load_h5ad_file
    raw_input = sc.read_h5ad(input_path)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
    constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/anndata/readwrite/read.py", line 502, in _read_args_from_h5ad
    return AnnData._args_from_dict(d)
  File "/opt/conda/envs/scaden/lib/python3.6/site-packages/anndata/core/anndata.py", line 2157, in _args_from_dict
    if key in d_true_keys[true_key].dtype.names:
AttributeError: 'dict' object has no attribute 'dtype'

```
Any Idea?

All the best,

Vincent

**Comment by KevinMenden** [comment]
Hi Vincent!

Yes, I just added the `simulate` command over the weekend - and there have been some issue with building the docker image. I will try to resolve this as soon as I get to it, hopefully tonight or tomorrow. So hopefully you will be able to have a working docker image tomorrow!

Regarding the other failures - I can only assume that something went wrong with the creation of the input files. The easiest way is to just use Scaden. So I'll try to make sure that you can actually do that :) 

Will let you know here once I know more.

**Comment by vdet** [comment]
Thanks Kevin!

FYI, I had to run this within the container:
```
pip install pandas
pip install anndata
```
to get the *py scripts working.

All the best,

Vincent

**Comment by KevinMenden** [comment]
Thanks! Yeah something was really off ...
Anyhow - I pushed a container with the latest Scaden version (v0.9.5).

So with `docker pull kevinmenden/scaden` you should now get the latest version :) 

Now regarding your other question - the h5ad is written using the `anndata` package, and thus contains their format, which was designed for single cell data:
https://anndata.readthedocs.io/en/latest/index.html

It contains the count matrix from the simulate data files, the cell composition for every sample, and also a 'ds' field specifying the dataset the sample belongs to, which is useful if you have several datasets stored in the file.

The simulate function contains two steps, as you noticed - I could send you some toy examples of the first step, which creates the simulated bulk?
From your error message it looks like there were some issue which the h5ad file, something I could not replicate yet, as this function works fine for me.

**Comment by vdet** [comment]
Hi Kevin,

The container is working, thanks a lot!

It is explained in [this page](https://github.com/KevinMenden/scaden/blob/master/docs/usage.md):

> Scaden to find your datasets and use them for simulation, they should be stored in the same directory and must be formatted like this:
> 
> <dataset_name>_.txt for the count data
> 
> <dataset_name>_celltypes.txt for the cell type labels

When I did that, however:
```
 ll
total 360784
drwxr-xr-x 4 root root       136 Dec 15 08:28 ./
drwxr-xr-x 3 root root       102 Dec 11 16:49 ../
-rw-r--r-- 1 root root 369286804 Dec 15 08:08 PTC7SN1_.txt
-rw-r--r-- 1 root root    155260 Dec 15 08:08 PTC7SN1_celltypes.txt
# scaden simulate --cells 100 --n_samples 10 --data ./ --pattern PTC7SN1
2020-12-15 08:28:57.316270: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-12-15 08:28:57.316393: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

     ____                _            
    / ___|  ___ __ _  __| | ___ _ __  
    \___ \ / __/ _` |/ _` |/ _ \ '_ \ 
     ___) | (_| (_| | (_| |  __/ | | |
    |____/ \___\__,_|\__,_|\___|_| |_|

    
ERROR:root:No datasetes fround! Have you specified the pattern correctly?
```
removing the `--pattern` argument also generate an error. Same if I `mv PTC7SN1_.txt PTC7SN1.txt`. Am I missing something?

All the best,

Vincent

**Comment by KevinMenden** [comment]
Hi Vincent, sorry for the late reply!

Glad the image works now.

You have to specify the pattern like this: `*_norm_counts_all.txt`

For instance, say you have a `test` dataset, then you should have two files for this named like this:
`test_counts.txt`
`test_celltypes.txt`

And in this case, your pattern would be `*_counts.txt`
Hope that makes sense. You can get some hlep for the parameters by using:
`scaden simulate --help`

Best,
Kevin

**Comment by vdet** [comment]
Dear Kevin,

I could run the simulate-train-predict pipeline.

So guess we can close this one. Thanks a lot for your help.

Vincent
