### ISSUE TITLE
Scaden simulate error: KeyError: 'Celltype'

### ISSUE THREAD

**Issue by MarcusLCC** [KevinMenden/scaden#52]
Hi,

Thanks for your great work on scaden.

I've been recently trying to use scaden to recognize cell fractions. With the newly released Scaden v0.9.5, I tried to run the 'scaden simulate' command but resulted in the same error showing something wrong with 'Celltype'.

Log/Error is:
`Datasets: ['']
Loading  dataset ...
No. of common genes: 14003
Merging unknown cell types: ['unknown']
Traceback (most recent call last):
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Celltype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/bin/scaden", line 8, in <module>
    sys.exit(main())
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/scaden/__main__.py", line 31, in main
    cli()
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/scaden/__main__.py", line 211, in simulate
    simulation(
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/scaden/preprocessing/simulate.py", line 13, in simulation
    simulate_bulk(
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/scaden/preprocessing/bulk_simulation.py", line 308, in simulate_bulk
    ys[i] = merge_unkown_celltypes(ys[i], unknown_celltypes)
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/scaden/preprocessing/bulk_simulation.py", line 194, in merge_unkown_celltypes
    celltypes = list(y["Celltype"])
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/disk1/marcus/Le/scaden_analysis/scaden-0.9.5/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Celltype'
`

My command for 'scaden simuate' is:
`scaden simulate --cells 150 --n_samples 1000 --data ../ --pattern _.txt`

The count data file '_.txt' has been generated following the normalization steps of your example in jupyter script, containing 14003 genes (column) and 2298 cells (row). Formatted as follows (I've also tried to replace the row name with barcodes, or set the genes as row and cells as column, however the error is the same):

![image](https://user-images.githubusercontent.com/61820820/102242061-a0968380-3f34-11eb-8218-1531b38cd101.png)

And the _celltypes.txt has following format (2298 rows. Actually I was not sure about the 'n x 2' format mentioned in your tutorial, whether to add column name and row name. So I've tried to add column name or/and row name to this file but the error appears to be the same.):

![image](https://user-images.githubusercontent.com/61820820/102241953-83fa4b80-3f34-11eb-9fee-fefea8aa5493.png)

I suppose something is wrong with the format, but have tried several times and couldn't figure out the reason.
May I have your suggestion on this issue? Thanks a lot!

Marcus

**Comment by KevinMenden** [comment]
Hi Marcus,

I'm sorry you had so much trouble getting Scaden to run!
Of course I'll help you out. It might very well be that some errors made their way into the new release :) 

At first glance your dataset looks good - just two questions:
* ist there a column named 'Celltype' (capital C) in your *celltypes.txt file? That's actually the only one you need - will update the docs soon.
* could you try specifying the pattern as *_.txt?

I'll have a better look in a bit!

Best,
Kevin

**Comment by MarcusLCC** [comment]
Thanks for your reply, Kevin. I appreciate it very much.

1. Yes I have tried to add the column name to the celltypes file with 'Label' and 'Celltype' (capital C) respectively for the 2 columns, and the error was the same.
2. Initially I named the file with prefix like 'AMLD0_.txt' and 'AMLD0_celltypes.txt', after which I used the parameter
`--pattern AMLD0`
and got the error like this
![image](https://user-images.githubusercontent.com/61820820/102247998-a5ab0100-3f3b-11eb-82a7-d5a1c0319446.png)

Then I tried to use the full name in parameter. I named the file as 'sc_.txt' and 'sc_celltypes.txt' and called
`--pattern sc_.txt`
and the last line of the log was:
![image](https://user-images.githubusercontent.com/61820820/102248719-73e66a00-3f3c-11eb-8dcc-607895e9f08b.png)

Then I named the file as '_.txt' and '_celltypes.txt' and called '--pattern _.txt', and it successfully loaded the count file, with some issue on the celltypes file.

Hope this info helps.


Best,
Marcus

**Comment by KevinMenden** [comment]
Okay perfect, yes that helps - I will try to replicate the issue. Could you provide me with either some part of your celltypes file? (e.g. the first few rows), or a screenshot of the header?

**Comment by MarcusLCC** [comment]
Hi, Kevin

Here is the first 20 row of the celltypes file

Label  Celltype
AML556-D0_AAAAAGGGATAN	ProMono-like
AML556-D0_AAAACCGAGGAT	ProMono-like
AML556-D0_AAAAGATGAGCG	Mono-like
AML556-D0_AAAAGCGTGGTG	ProMono-like
AML556-D0_AAAAGTAGCATA	ProMono-like
AML556-D0_AAAATCGGAATA	ProMono-like
AML556-D0_AAAATGCGGGAC	ProMono-like
AML556-D0_AAACATGCGAGN	Mono-like
AML556-D0_AAACATGCTTTN	Mono-like
AML556-D0_AAACGTCCTAGC	Mono-like
AML556-D0_AAACGTTACGGT	Mono-like
AML556-D0_AAACTAGAAAAC	Plasma
AML556-D0_AAACTCGCGTTG	Mono-like
AML556-D0_AAAGATCCATTN	ProMono-like
AML556-D0_AAAGCACGATTN	ProMono-like
AML556-D0_AAAGCTCATGGA	ProMono-like
AML556-D0_AAAGGAGACGGT	ProMono-like
AML556-D0_AAAGTTCCACAG	Mono-like
AML556-D0_AAATACGACATG	Prog
AML556-D0_AAATAGTAAGCA	NK

The screenshot is as follows:



Best,
Marcus

**Comment by MarcusLCC** [comment]
Hi Kevin,

I've checked my data again and find that the 'TAB' between header 'Label' and 'Celltype' was malformatted. I used mobaxterm text editor to add the header and that resulted in the 'tab' discrepancy. 
After I replace the TAB with vim it works well with '--pattern _.txt' !

Sorry for the inconvenience caused and thanks a lot for your reply. I'm able to try the next steps with Scaden now!


Best,
Marcus

**Comment by KevinMenden** [comment]
Hi Marcus,

awesome - glad to hear it works now! Was happy to help :-) 

I already made some plans to make the parsing of the celltype data more flexible and also robust, currently it's definitely a bit picly.

So thanks for bringing that up 👍 

Best,
Kevin
