### ISSUE TITLE
Error when running simulate 

### ISSUE THREAD

**Issue by RK1912** [KevinMenden/scaden#74]
Hi , 
I am trying to run Scaden simulate for my data . 
This is how my data looks currently :
data_counts.txt : 2627 rows (cell types )  and 26405 columns ( genes )
data_celltypes.txt : 2627 cell type labels corresponding to the rows in data_counts.txt.

When I run the command 
```
scaden simulate --data data_scaden/ -n 100 --pattern "*_counts.txt"

```
I get the following output and the .h5ad file is not created:
```
Datasets: ['data']
Loading data dataset ...
Index(['Celltype'], dtype='object')
CRITICAL:root:No common genes found. Exiting.

```

Please let me know if I am going wrong somewhere? and How I can fix this ?

Thanks , 
RK

**Comment by KevinMenden** [comment]
Hi RK,

this looks like a formatting issue. Can you quickly run
`scaden example` 
And check whether your data has a similar format as the example data that is generated?

**Comment by RK1912** [comment]
Hi Kevin, 
I checked and realized it was because I had created the file with R and it didnt read in properly. I fixed it and was able to generate the training sets. But I have a new error now:

```
Datasets: ['data']
Loading data dataset ...
Index(['Celltype'], dtype='object')
No. of common genes: 26404
Merging unknown cell types: ['unknown']
Available celltypes: ['SC-T3', 'SC-T1', 'SC-B1', 'SC-M2', 'SC-B4', 'SC-M3', 'SC-B2', 'SC-F1', 'SC-T6', 'SC-F4', 'SC-M4', 'SC-M1', 'SC-T4', 'SC-F3', 'SC-F2', 'SC-T2', 'SC-T5', 'SC-B3']
Subsampling data...
Normal samples: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:29<00:00,  1.70it/s]
Sparse samples: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.28it/s]
Finished!
Celltypes: ['SC-T3', 'SC-T1', 'SC-B1', 'SC-M2', 'SC-B4', 'SC-M3', 'SC-B2', 'SC-F1', 'SC-T6', 'SC-F4', 'SC-M4', 'SC-M1', 'SC-T4', 'SC-F3', 'SC-F2', 'SC-T2', 'SC-T5', 'SC-B3']
Found datasets: ['data', 'example']
Processing data
c:\users\rk\anaconda3\lib\site-packages\anndata\_core\anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
Traceback (most recent call last):
  File "c:\users\rk\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rk\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rk\Anaconda3\Scripts\scaden.exe\__main__.py", line 7, in <module>
  File "c:\users\rk\anaconda3\lib\site-packages\scaden\__main__.py", line 33, in main
    cli()
  File "c:\users\rk\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\rk\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\rk\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rk\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rk\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rk\anaconda3\lib\site-packages\scaden\__main__.py", line 176, in simulate
    simulation(simulate_dir=out,
  File "c:\users\rk\anaconda3\lib\site-packages\scaden\simulate.py", line 20, in simulation
    create_h5ad_file(simulate_dir, out_name, unknown_celltypes)
  File "c:\users\rk\anaconda3\lib\site-packages\scaden\preprocessing\create_h5ad_file.py", line 92, in create_h5ad_file
    y = sort_celltypes(y, labels, celltypes)
  File "c:\users\rk\anaconda3\lib\site-packages\scaden\preprocessing\create_h5ad_file.py", line 61, in sort_celltypes
    idx = [labels.index(x) for x in ref_labels]
  File "c:\users\rk\anaconda3\lib\site-packages\scaden\preprocessing\create_h5ad_file.py", line 61, in <listcomp>
    idx = [labels.index(x) for x in ref_labels]
ValueError: 'SC-T3' is not in list

```
Could you please help me figure this out?
Thanks!

**Comment by KevinMenden** [comment]
Hi,

the issue seems to be that a celltype in your reference celltype list is not in you simulated data.
Could you give me the exact commands you have been using so far?

Thanks!

**Comment by RK1912** [comment]
Hi Kevin 

I ran the following command:
```
scaden simulate --data zhang_data/ -n 100 --pattern "*_counts.txt"

```
Here is the data I used:
https://drive.google.com/drive/folders/15XDsJkbaM_LipLKVk2Ui9JYekkXG0ytU?usp=sharing

Let me know if you need anything else . 

Thanks

**Comment by RK1912** [comment]
Hi 
Sorry for the trouble , 
But now I am able to create the data.h5ad and processed.h5ad files. 
However when I run scaden train , I get the following error:

```
Traceback (most recent call last):
  File "c:\users\ramya.mallela\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ramya.mallela\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ramya.mallela\Anaconda3\Scripts\scaden.exe\__main__.py", line 7, in <module>
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\scaden\__main__.py", line 33, in main
    cli()
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\scaden\__main__.py", line 76, in train
    training(data_path=data_path,
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\scaden\train.py", line 64, in training
    cdn256.train(input_path=data_path, train_datasets=train_datasets)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\scaden\model\scaden.py", line 295, in train
    self.logits = self.model(x, training=True)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 998, in __call__
    input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
  File "c:\users\ramya.mallela\anaconda3\lib\site-packages\tensorflow\python\keras\engine\input_spec.py", line 255, in assert_input_compatibility
    raise ValueError(
ValueError: Input 0 of layer sequential is incompatible with the layer: expected axis -1 of input shape to have value 100 but received input with shape (128, 26404)

```

Please let me know how I can fix this 

Thanks 
Rk

**Comment by KevinMenden** [comment]
Hi RK,

glad you fixed it - I will look into this, it shouldn't be so easy to break.
As far as I can tell you are running on windows, right? I fear that this might be the cause for your problems, because I couldn't directly find an issue with your data.

I will try to replicate the error locally!

**Comment by KevinMenden** [comment]
Okay I could run the command without changing anything in the celltypes file, so it is very likely something windows specific. If you can, try on any kind of unix-system (Mac or Linux).

One thing I noticed is that your .h5ad file was created using your data and the `example` data, so make sure you delete those example files from the folder before simulation and any other steps! That might cause the problem.



```
(base) kevin@kevins-mbp scaden_test % scaden simulate --data deconv_data -n 100 --pattern "*_counts.txt"

     ____                _            
    / ___|  ___ __ _  __| | ___ _ __  
    \___ \ / __/ _` |/ _` |/ _ \ '_ \ 
     ___) | (_| (_| | (_| |  __/ | | |
    |____/ \___\__,_|\__,_|\___|_| |_|

    
Datasets: ['data']
Loading data dataset ...
Index(['Celltype'], dtype='object')
No. of common genes: 26404
Merging unknown cell types: ['unknown']
Available celltypes: ['SC_B4', 'SC_F2', 'SC_M4', 'SC_T3', 'SC_T1', 'SC_B3', 'SC_F4', 'SC_T4', 'SC_F3', 'SC_F1', 'SC_T6', 'SC_T2', 'SC_B2', 'SC_M3', 'SC_T5', 'SC_M1', 'SC_B1', 'SC_M2']
Subsampling data...
Normal samples: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:18<00:00,  2.71it/s]
Sparse samples: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:11<00:00,  4.54it/s]
Finished!
Celltypes: ['SC_B4', 'SC_F2', 'SC_M4', 'SC_T3', 'SC_T1', 'SC_B3', 'SC_F4', 'SC_T4', 'SC_F3', 'SC_F1', 'SC_T6', 'SC_T2', 'SC_B2', 'SC_M3', 'SC_T5', 'SC_M1', 'SC_B1', 'SC_M2']
Found datasets: ['data']
Processing data
/Users/kevin/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
... storing 'ds' as categorical

```

**Comment by RK1912** [comment]
Hi kevin, 

Thanks a lot for looking into this .
That is weird, because I have my data in a separate folder, though it says Found datasets: ['data', 'example']

**Comment by KevinMenden** [comment]
Exactly, that's a bit weird. Maybe make sure to delete everything example related and try again :)

**Comment by RK1912** [comment]
I am able to train the model. 
Just one more question:
How many models does it train on?

**Comment by KevinMenden** [comment]
Awesome :) 

Scaden trains three different DNNs for 5000 steps and then averages their predictions.

**Comment by RK1912** [comment]
Hi Kevin, 
I was successfully able to train the model , but I got the following error . 
Please note: I initially ran this on windows, but I also did another run on Ubuntu 18.04.5 .

```
2021-02-25 08:04:19.030342: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-25 08:04:19.030483: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-25 08:04:19.030500: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-25 08:04:19.030517: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (xxxx): /proc/driver/nvidia/version does not exist
2021-02-25 08:04:19.030721: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-25 08:04:19.031302: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-25 08:04:20.356815: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-25 08:04:20.376247: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2499995000 Hz

```
Let me know if there are any dependencies I am missions. Also, I am not using any GPU. 

Thanks !

**Comment by KevinMenden** [comment]
Okay wow you really collect all the errors 😁 

Alright, how did you install Scaden? 
Is there a possibility to just use the docker image I provide instead? This seems to be some system related issue.

**Comment by RK1912** [comment]
Haha! 
I installed Scaden with pip . 
I have some other issue with using docker currently due to the way its set up , which is why I had to install scaden. 

Okay - I will look into it . 
Do let me know if there is anything that can help. 

Thanks!

**Comment by KevinMenden** [comment]
Okay ... yes it looks like a problem with tensorflow, which has given me headaches in that area quite frequently.

Not really sure what the issue is and how to solve it. But you could try just uninstalling and re-installing tensorflow in your environment (so `pip uninstall tensorflow` and then `pip install tensorflow`), maybe that helps.

**Comment by KevinMenden** [comment]
Oh actually - you said you were able to train the model - did that run through? Could you make the prediction?
Those might just be extensive logging messages that you can ignore. I think I saw them before.

**Comment by RK1912** [comment]
Okay yes - nevermind . I just ran it and I think I have some predictions . 
Sorry for the trouble! and thanks once again!
