### ISSUE TITLE
Scaden example sometimes breaks

### ISSUE THREAD

**Issue by KevinMenden** [KevinMenden/scaden#85]

**Comment by shengqh** [comment]
I tried to generate example but failed.

```
scaden example

Traceback (most recent call last):
  File "/home/shengq2/.local/bin/scaden", line 8, in <module>
    sys.exit(main())
  File "/home/shengq2/.local/lib/python3.8/site-packages/scaden/__main__.py", line 47, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shengq2/.local/lib/python3.8/site-packages/scaden/__main__.py", line 247, in example
    exampleData(n_cells=cells, n_genes=genes, n_samples=samples, out_dir=out, n_types=types)
  File "/home/shengq2/.local/lib/python3.8/site-packages/scaden/example.py", line 37, in exampleData
    celltype_list = random.choices(celltypes, k=n_cells)
  File "/usr/lib/python3.8/random.py", line 399, in choices
    return [population[_int(random() * n)] for i in _repeat(None, k)]
  File "/usr/lib/python3.8/random.py", line 399, in <listcomp>
    return [population[_int(random() * n)] for i in _repeat(None, k)]
IndexError: list index out of range
```

**Comment by KevinMenden** [comment]
Hi @shengqh , thanks for reporting.
This is a known bug that I want to fix with the next release, which is probably coming around soon. You should be able to run again and usually it should not fail.

I'll fix this as soon as I find the time.
